#
# Build stage
#
FROM maven:3.6.0-jdk-11-slim AS build
COPY src /home/app/src
COPY pom.xml /home/app
RUN  mvn -f /home/app/pom.xml clean package

#
# Package stage
#
FROM openjdk:11-jre-slim
COPY /target/actuator-app-1.0.jar /app/actuator-app.jar
EXPOSE 8000
ENTRYPOINT ["java","-jar","/app/actuator-app.jar"]